### PR TITLE
GRAL Deterministic Model Option (in progress)

### PR DESCRIPTION
**Pull request by JoshLovesFun**
Add feature that allows GRAL to be run in "Deterministic Mode" based on an option in the final row of the "in.dat" input file.
Further work will attempt to update code that will allow a fixed set of random values to be used, so that the model can produce identical output with identical inputs. So far, my attempts have been unsuccessful and any help is greatly appreciated as this would allow a great enhancement to our research goals.

### CODE REVIEW

**Comment by MarkusKuntner** [comment]
I had a deterministic concept years ago, but it was rightfully rejected by the development team, I am therefore pleased that you are trying to create such a version. The background for the rejection was, that dispersion in the atmosphere is chaotic and the GRAL concept is intended to represent this chaotic effect.

If you want to create a deterministic GRAL, you have to consider that many procedures are processed in parallel. I would suggest giving each particle two seeds (UInt) that are modified after each use (e.g. once for the particle driver). This helps to avoid parallelization problems. And you need general seeds for things like the initial wind direction calculation within the wind sector.

Using these seeds, you can create a random number from 0-1, for example according to John D. Cook:
https://www.codeproject.com/Articles/25172/Simple-Random-Number-Generation

Another thing to consider: if you change sources (e.g. the source emission rate), the particle assignment changes and GRAL is no longer strictly deterministic, even if deterministic random generators are used. And the number of previously calculated situations would also affect the deterministic. The latter could be avoided by setting the respective seed of each particle depending on the current situation number.

Do not hesitate to contact me if you have any questions.

**Comment by JoshLovesFun** [comment]
Thanks for your reply and feedback. If I have more specific questions about the code, would you like me to respond here, or is there an email address I can use to contact you?

**Comment by MarkusKuntner** [comment]
GitHub is fine for code review and code discussions. If there are specific questions, you can comment the code and I will try to answer your questions.

**Comment by MarkusKuntner** [comment]
I have pushed small changes into your repo as a test, that works anyway. You are welcome to undo them again. I should have put this in a separate branch, then it would be clearer. Unfortunately, I don't use GitHub that often, and I always have to read up on the syntax.

**Comment by JoshLovesFun** [comment]
Thank you very much. I have made a new branch in my repo (Implementation) where I will be iteratively suggesting incorporation into the GRAL_Deterministic branch.

**Pull request closed without merging**
